### PR TITLE
Translation by gettext and translation in French implemented

### PR DESCRIPTION
**Pull request by Caccc**
Hi Simon,

You ll found here Translation by gettext and translation in French implemented.
Sunrise and sunset had been add to.

### CODE REVIEW

**Comment by simon04** [comment]
Hi!
Thanks for your contribution. I favour the pull request by ecyrbe due to additional improvements (autotools, gsettings).
One remark on your change regarding the colon: French is the only language I know which typesets a colon with space before and after the symbol. Many other languages only allow a space after the colon.
Regards,
Simon

**Comment by ecyrbe** [comment]
Freddy, you where answering on the bad pull request.you said on mine :

> The "2 points" => ":" must be exclude of the translation, same i had do.

That's wrong and that's what simon is telling you. You are doing this on your code :

this._currentWeatherAstronomy.text = _('Sunrise') + ' : ' + sunrise + ' - ' + _('Sunset') + ' : ' + sunset;

the space before ':' is only mandatory in french ('espace inséccable'). In english, you don't prefix ':' with space.
you should let the translator do the typography and use a format()or sprintf() like funtion, that put parameters outside of the text to translate like this :
this._currentWeatherAstronomy.text = _('Sunrise: %1 - Sunset: %2).format(sunrise,sunset);

**Comment by Caccc** [comment]
Yep right, but i had do that in 1 hour, not past long time on.
I wait your merge on the original.

So with gsetting now, try to integrate the option in gnome tweak tools.

Last think, people hate compiling something and prefer copy past extension, or this extension must be intergate totally in gnome shell.

**Comment by simon04** [comment]
> Last think, people hate compiling something and prefer copy past extension

I partially agree. Installation was easier without autogen, but at the same time no clean configuration with gsettings was possible.

> or this extension must be intergate totally in gnome shell.

I see little change for an integration in plain GNOME Shell. But it's down to linux distributions to provide packages for common extensions. E.g., for Arch Linux there exist [several extensions in AUR](http://aur.archlinux.org/packages.php?K=gnome-shell-).

Btw: I consider integrating the values for sunrise and sunset.

**Comment by Caccc** [comment]
> but at the same time no clean configuration with gsettings was possible

Not need to compile with pyton see the package gnome tweak tool

**Pull request closed without merging**
