### PR TITLE
Fix the weather URL

### PR DESCRIPTION
**Pull request by robinbowes**
The weather URL didn't work for me. This commit changes it to something that works, but the pop-up still doesn't look quite right (the forecast is not working)

### CODE REVIEW

**Comment by simon04** [comment]
With which WOEID (aka. ID) did you experience this problem?

**Comment by robinbowes** [comment]
This is the URL I got the ID From:

http://weather.yahoo.com/england/north-yorkshire/carlton-husthwaite-28201191/?unit=c

**Comment by simon04** [comment]
Strange ... one of the following URLs works, but when interchanging w and p it breaks:
http://weather.yahooapis.com/forecastjson?w=28201191
http://weather.yahooapis.com/forecastjson?p=UKXX1224

As a quick solution you could use UKXX1224 as WOEID.

**Comment by robinbowes** [comment]
I'll give that a go. Where did you get UKXX1224 from?

**Comment by simon04** [comment]
It is contained in the first request (`location.location_id`).

**Comment by robinbowes** [comment]
OK, that's working better.

The forecast looks OK, but I see a cloud with an orange exclamation mark in the bar and the ext "unknown"

**Comment by simon04** [comment]
I added some code to automatically detect "wrong" WOEIDs and correct them as explained before. Please test! :-)

> but I see a cloud with an orange exclamation mark in the bar and the ext "unknown"

Does this error still occur (after my changes of today)? If so, please post a screenshot.

**Comment by robinbowes** [comment]
OK, I pulled the latest code and installed it (it took a while to work out that I needed glib2-devel installed).

I configured using:

gsettings set org.gnome.shell.extensions.weather woeid UKXX1224
gsettings set org.gnome.shell.extensions.weather unit celsius

and restarted gnome-shell (Alt-F2, r)

I see a greyish rectangle with a turned-up corner as the icon, but the forecast seems to work OK.

Clicking on the applet brings up the weather forecast; the icons seem to work OK for that.

Am I using the write WOEID? ie. the xxxxnnnn format rather than all numbers?

R.

**Comment by simon04** [comment]
> gsettings set org.gnome.shell.extensions.weather woeid UKXX1224
> Am I using the write WOEID? ie. the xxxxnnnn format rather than all numbers?

Yes.

> I see a greyish rectangle with a turned-up corner as the icon, but the forecast seems to work OK.
> Clicking on the applet brings up the weather forecast; the icons seem to work OK for that.

To summarize, the forecast icon work, but not the icons for the current condition? You could experiment with the `use-symbolic-icons` setting (see [Readme](https://github.com/simon04/gnome-shell-extension-weather))

**Comment by robinbowes** [comment]
Actually, it's working now. Perhaps it was some caching issue, or only some weather conditions are broken?

**Comment by simon04** [comment]
I also encountered problems with symbolic weather icons. This was changed recently (in favour of `use-symbolic-icons` setting). I think, I can close this request.

**Comment by robinbowes** [comment]
Simon, it seems to be intermittent - sometimes the "Partially cloudy" icon displays fine, sometimes I just see the rectangle. Not sure what's going on.

**Comment by simon04** [comment]
This should be fixed in 232117f6b79e4ba81455.

**Pull request closed without merging**
