### PR TITLE
improves translation, packagin and settings

### PR DESCRIPTION
**Pull request by ecyrbe**
this is an improves version that add :
- translation
- autotools for packaging
- gsettings for configuration

### CODE REVIEW

**Comment by Caccc** [comment]
Same i anderstand nothing to github to send file, you have translation with gettext in French here : https://rapidshare.com/files/1266274045/caccc_weather_venemo.net.tar.gz

weather@venemo.net/extension.js
weather@venemo.net/metadata.json
weather@venemo.net/stylesheet.css
weather@venemo.net/locale/fr_FR/LC_MESSAGES/weather.mo
Sunrise & sunset had be add

This is the Better version for this moment

Perview here : http://img219.imageshack.us/img219/1997/capture2qh.png

**Comment by simon04** [comment]
Thank you all very much for your great work! I'm going to merge this set of changes soon.
Currently, I see two issues:
1. As far as I see it, the weather code and the condition string do not always carry the same information. E.g., for Innsbruck the condition is "PM Thunderstorms" which is lost when translating it using `get_weather_condition`. I could not find a list containing all possible condition strings. What do you think about adding a config flag indicating whether the weather condition should be translated?
2. Why truncate the string in `get_locale_day`, or, put differently, can you be sure that the translated string can be truncated to the length of the untranslated one?
I'm looking forward to hearing your comments on these issues!
Simon

**Comment by ecyrbe** [comment]
thank you very much, for the remaining bugs :
1 : yes,  that could be a solution.
2 : i truncated it, because gnome does it, and i wanted it to have the same behaviour. however, i've not looked at the gnome date code to see how they deal with the truncation in other langages that need more than 3 characters. May be Just let the translators do the job of truncating, and get rid of it in the the code.

**Comment by Caccc** [comment]
Hello Simon,

1 - The yahoo documentation is obsolete for the correct icons and translation.
2 - I don t anderstand what you want mean, explain me more ...

Freddy

**Comment by ecyrbe** [comment]
Freddy,
the questions were obviouly for me, as the pull request was made by me.
you can create another pull request for your changes.

**Comment by Caccc** [comment]
Ok, so why i receive the mail ?

The "2 points" => ":" must be exclude of the translation, same i had do.

**Comment by ecyrbe** [comment]
Hi Freedy,
you are receiving these e-mails because you posted a comment on this pull request.
you can check for notifications when you are logged on github.

**Comment by simon04** [comment]
For clarification: The discussion between Caccc and ecyrbe is based on another [pull request](https://github.com/simon04/gnome-shell-extension-weather/pull/4).

---

> 1 : yes, that could be a solution.

As you already provided the other settings in gconfig, would you like to integrate this one as well? 

> 2 : i truncated it, because gnome does it, and i wanted it to have the same behaviour. however, i've not looked at the gnome date code to see how they deal with the truncation in other langages that need more than 3 characters. May be Just let the translators do the job of truncating, and get rid of it in the the code.

Personally, I'd favour to write out the days in full, i.e., not truncating them.

**Comment by simon04** [comment]
Thanks again! I merged the changes and tackled my two issues (dropped truncating the day of week names and added translate-condition to the gconfig settings).

**Pull request merged**
