### PR TITLE
Link location to full Yahoo weather page (issue #18) - gnome 3.2 version

### PR DESCRIPTION
**Pull request by aripollak**
This is just pull request #34, but against master. I needed to make a slight modification to make it work with the latest version, since the request format had changed.

### CODE REVIEW

**Comment by aripollak** [comment]
I updated this to fix a problem where the details page was getting opened multiple times.

**Comment by simon04** [comment]
Sorry for not responding to this pull request sooner. I'm not happy with the visual appearance of this link. I'd prefer either a small icon in the top right corner (below the configuration icon), or the plain location name that is bolded or highlighted on hover (similar to the texts in the panel).

**Comment by aripollak** [comment]
For the link option, can it say "<Location>..." with ellipses to give some indication that it's a link?

**Comment by simon04** [comment]
That's okay by me … :-)

**Comment by aripollak** [comment]
Not sure if github sends notifications for new commits here; just updated the branch to match your requested behavior.

**Pull request merged**
